spring:
datasource:
url: jdbc:h2:mem:organt;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
driver-class-name: org.h2.Driver
username: sa
password: ''
h2:
console:
enabled: true
path: /h2
jpa:
hibernate:
ddl-auto: update
properties:
hibernate.format_sql: true
hibernate.jdbc.time_zone: UTC
thymeleaf:
cache: false

server:
error:
include-message: always

# Exemplo de profile p/ Postgres (prod):
# ---
# spring:
# config:
# activate:
# on-profile: prod
# datasource:
# url: jdbc:postgresql://localhost:5432/organt
# username: organt
# password: organt
# jpa:
# hibernate:
# ddl-auto: update